# for snekmer main
# commit 2ca0bb84fd4be1d7e558e2b548f738b5b104dbe9
# nose and jsonrpcbase are required by kbase
name: snekmer
channels:
  - anaconda
  - bioconda
  - numba
  - conda-forge
dependencies:
  - python >= 3.9
  - biopython
  - jinja2
  - matplotlib
  - nose
  - numpy >= 1.22.3
  - numba >= 0.56
  - scipy
  - pandas
  - seaborn
  - scikit-learn
  - snakemake == 7.0
  - umap-learn
  - hdbscan
  - pip
  - pip:
      - jsonrpcbase
      - git+https://github.com/PNNL-CompBio/Snekmer.git@2ca0bb84fd4be1d7e558e2b548f738b5b104dbe9